# Generated by Django 4.1.2 on 2022-10-10 18:37

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='VIN',
            fields=[
                ('id', models.CharField(max_length=200, primary_key=True, serialize=False, unique=True)),
                ('year', models.IntegerField(null=True)),
                ('make', models.CharField(max_length=50, null=True)),
                ('model', models.CharField(max_length=50, null=True)),
                ('type', models.CharField(max_length=50, null=True)),
                ('color', models.CharField(max_length=50, null=True)),
                ('weight', models.JSONField(default=dict)),
                ('dimensions', models.JSONField(default=dict)),
            ],
        ),
    ]
