version: "3.9"

services:
  db:
    image: postgres:latest
    ports:
      - "5434:5432"
    restart: always
    volumes:
      - ./data/db:/var/lib/postgresql/data
    environment:
      - POSTGRES_USER=postgres_user
      - POSTGRES_PASSWORD=postgres_password
  web:
    build: .
    command: python manage.py runserver 0.0.0.0:8000
    env_file:
      - ./.env
    volumes:
      - .:/code
    ports:
      - "8000:8000"
    environment:
      - POSTGRES_DB=postgres_user
      - POSTGRES_USER=postgres_user
      - POSTGRES_PASSWORD=postgres_password
    depends_on:
      - db